### ISSUE TITLE
Allow creating new track with existing file

### ISSUE THREAD

**Issue by Jiu9Shen** [tripal/tripal_jbrowse#45]
Sometimes we want to display one file with different types in different tracks. Tripal_jbrowse won't allow this because of file validation function. 
For example,
[BigWig tracks](http://jbrowse.org/docs/bigwig.html) can display in XYPlot, density, coverage, or heatmap

**Comment by laceysanderson** [comment]
I tested this issue with a VCF which already existed and received the following errors:
<img width="1202" alt="Screen Shot 2020-02-14 at 1 29 54 PM" src="https://user-images.githubusercontent.com/1566301/74561404-1ce3c300-4f2e-11ea-8cc0-230ac5bac61c.png">

**This applies to both symbolic link and copying of files.**

**Comment by laceysanderson** [comment]
The concern relates to the following use case:
> First I create a track with version 1.0 of my file (i.e. testfile.gff). Then I make a small change and create a new track with the same file (still testfile.gff but with a different format for attributes). My intent is to test which version accomplishes what I want.

This use case is currently not possible using Tripal JBrowse and there is a good argument for whether it should be since the file is not the same (it just has the same name).

However, consider this use case:
> I have RNAseq data which I want to display with both a coverage and heatmap plot. In this case I want to create two tracks using the same file.

My suggestion for how to support the second case is to allow creation of a track where symbolic link option is selected even if the link already exists in the JBrowse. This is safe since both tracks are supposed to link to the same data.

## Plan
A. For uploaded files
Check if the file already exists and if so, provide a validation error. In this error tell the admin that if they need two tracks with the same data, the are advised to use the symbolic link option.

B. For symbolic link
- If the file does not exist, create the symbolic link.
- If it does exist (either through upload or symbolic link) then do not recreate the link and happily continue without error.
